# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [canary, rc]

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Setup Deno ${{ matrix.bun-version }}
        uses: denoland/setup-deno@v1.5.1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Test
        run: |
          echo 'SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }}' > ./.env
          deno install -D
          deno task build
          deno task coverage:deno

  test-bun:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [latest, 1.1]

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Use Bun.js ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Get Dependencies
        run: bun install

      - name: Run Coverage and Lint
        run: |
          echo 'SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }}' > ./.env.test.local
          bun run coverage

  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 22.x]

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Get Dependencies and Build
        run: pnpm install && pnpm build

      - name: Run Coverage and Lint
        run: |
          echo 'SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }}' > ./.env.test.local
          pnpm coverage:nodejs
