# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test-deno:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [canary, rc]

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Deno ${{ matrix.bun-version }}
        uses: denoland/setup-deno@v1.5.1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Test
        run: |
          echo 'SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }}' > ./.env
          deno install
          deno task coverage:deno
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [latest, 1.1]

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Bun.js ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Get Dependencies
        run: bun install

      - name: Run Coverage and Lint
        run: |
          echo 'SAUCENAO_TOKEN=${{ secrets.SAUCENAO_TOKEN }}' > ./.env.test.local
          bun run coverage
